package com.ieltsmastermind.practice.content.management.domain.enums;

public enum PracticeTopicTag {

    EDUCATION_AND_LEARNING,
    WORK_JOBS_AND_CAREERS,
    TECHNOLOGY_INTERNET_AND_AI,
    HEALTH_HEALTHCARE_AND_LIFESTYLE,
    ENVIRONMENT_CLIMATE_AND_SUSTAINABILITY,
    GOVERNMENT_LAW_AND_PUBLIC_POLICY,
    SOCIETY_SOCIAL_BEHAVIOR_AND_VALUES,
    FAMILY_CHILDREN_AND_AGEING,
    MEDIA_ADVERTISING_AND_COMMUNICATION,
    CULTURE_ART_TRADITIONS_AND_LANGUAGE,
    TRAVEL_TOURISM_AND_TRANSPORT,
    HOUSING_CITIES_AND_URBAN_RURAL_LIFE,
    SCIENCE_RESEARCH_AND_INNOVATION,
    BUSINESS_ECONOMY_AND_CONSUMER_BEHAVIOR,
    FOOD_AGRICULTURE_AND_FARMING,
    SPORT_LEISURE_AND_HOBBIES,
    HISTORY_ARCHAEOLOGY_AND_HERITAGE,
    ENERGY_NATURAL_RESOURCES_AND_INFRASTRUCTURE,
    CRIME_SAFETY_AND_SECURITY,
    GLOBALISATION_MIGRATION_AND_INTERNATIONAL_DEVELOPMENT,
    POPULATION_AND_DEMOGRAPHICS,
    ANIMALS_AND_WILDLIFE
}