package com.ieltsmastermind.practice.attempt.management.domain.enums;

public enum WritingFeedbackLabel {

    // Strength labels
    // Task Response / Task Achievement
    FULL_TASK_COVERAGE,
    CLEAR_POSITION,
    CONSISTENT_POSITION,
    RELEVANT_IDEAS,
    GOOD_IDEA_DEVELOPMENT,
    ADEQUATE_SUPPORT,
    APPROPRIATE_FORMAT,
    SUFFICIENT_LENGTH,

    // Task 1
    CLEAR_OVERVIEW,
    GOOD_KEY_FEATURE_SELECTION,
    GOOD_DATA_SUPPORT,

    // Task 2
    CLEAR_CONCLUSION,

    // Coherence & cohesion
    LOGICAL_ORGANISATION,
    CLEAR_PROGRESSION,
    EFFECTIVE_PARAGRAPHING,
    EFFECTIVE_COHESIVE_DEVICES,
    NATURAL_LINKER_USE,
    GOOD_REFERENCE_USE,
    MINIMAL_REPETITION,
    CLEAR_PARAGRAPH_FOCUS,

    // Lexical resource
    VARIED_VOCABULARY,
    PRECISE_VOCABULARY,
    APPROPRIATE_WORD_CHOICE,
    GOOD_COLLOCATION,
    APPROPRIATE_STYLE,
    GOOD_SPELLING,
    GOOD_WORD_FORMATION,
    NATURAL_LANGUAGE_USE,

    // Grammar
    VARIED_SENTENCE_STRUCTURES,
    GOOD_COMPLEX_STRUCTURE_USE,
    GRAMMAR_WELL_CONTROLLED,
    GOOD_PUNCTUATION,
    WELL_FORMED_SENTENCES,

    // Weakness labels
    // Task Response / Task Achievement
    PARTIAL_TASK_COVERAGE,
    UNCLEAR_POSITION,
    INCONSISTENT_POSITION,
    IRRELEVANT_IDEAS,
    INSUFFICIENT_IDEA_DEVELOPMENT,
    INSUFFICIENT_SUPPORT,
    INAPPROPRIATE_FORMAT,
    UNDER_LENGTH_RESPONSE,

    // Task 1
    MISSING_OVERVIEW,
    MISSING_KEY_FEATURES,
    INSUFFICIENT_DATA_SUPPORT,

    // Task 2
    WEAK_CONCLUSION,

    // Coherence & cohesion
    WEAK_ORGANISATION,
    UNCLEAR_PROGRESSION,
    WEAK_PARAGRAPHING,
    MISUSED_COHESIVE_DEVICES,
    OVERUSE_OF_LINKERS,
    UNCLEAR_REFERENCING,
    REPETITION,
    UNCLEAR_PARAGRAPH_FOCUS,

    // Lexical resource
    LIMITED_VOCABULARY,
    IMPRECISE_VOCABULARY,
    INAPPROPRIATE_WORD_CHOICE,
    WEAK_COLLOCATION,
    STYLE_INAPPROPRIATE,
    SPELLING_ERRORS,
    WORD_FORMATION_ERRORS,
    MEMORISED_LANGUAGE_OVERUSE,

    // Grammar
    LIMITED_GRAMMATICAL_RANGE,
    FAULTY_COMPLEX_SENTENCES,
    GRAMMAR_ERRORS,
    PUNCTUATION_ERRORS,
    SENTENCE_FRAGMENT_OR_RUN_ON
}